# Generated by Django 5.2.9 on 2026-01-21 09:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enable_cod', models.BooleanField(default=True, help_text='Allow customers to pay with Cash on Delivery', verbose_name='Enable Cash on Delivery')),
                ('free_delivery_threshold', models.DecimalField(decimal_places=2, default=500, help_text='Minimum order value for free delivery', max_digits=10, verbose_name='Free Delivery Above')),
                ('standard_delivery_charge', models.DecimalField(decimal_places=2, default=50, help_text='Delivery charge for orders below threshold', max_digits=10, verbose_name='Standard Delivery Charge')),
                ('store_open', models.BooleanField(default=True, help_text='Set to False to temporarily close the store for new orders', verbose_name='Store Open')),
                ('maintenance_mode', models.BooleanField(default=False, help_text='Enable maintenance mode to display a maintenance message', verbose_name='Maintenance Mode')),
                ('maintenance_message', models.TextField(blank=True, default='We are currently under maintenance. Please check back soon!', verbose_name='Maintenance Message')),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('contact_phone', models.CharField(blank=True, max_length=20)),
                ('whatsapp_number', models.CharField(blank=True, max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='settings_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
        ),
    ]
